---
- name: Install and Configure the Agent in vadmin Server
  hosts: all
  become: true

  tasks: 
    - name: Configure Agent
      shell: "/usr/local/bin/dicmd import -u admin \
                        -w admin \
                        -p PCInstall_Check \
                        -l Development \
                        -s datapoint=reuse,dataobject=reuse \
                        -f '/home/vadmin/demo_jenkins/job_full_load_dynamic_cas.json'"
      register: purple_agent
    - name: Validate Agent configuration 
      debug: var=purple_agent